### PR TITLE
fix: Changed "In Review" flag styling

### LINKED ISSUE #339: Update tag styling on homepage so it doesn't hurt user's eyes
## Use Case
The high contrast tag background color may hurt user's eyes causing pain and general distrust in the application.
Screenshot 2024-12-05 at 3 07 06 PM

## Solution
The tag should likely avoid purple due to color contrast issues as well as looking too much like a tiny button.
Please update the following:
- font weight and color
- div element's height, border and background
Screenshot 2024-12-05 at 3 40 50 PM
Screenshot 2024-12-05 at 3 41 07 PM

Solid background styling below would be an equally reasonable option but designer slightly prefers the one with the border.
Screenshot 2024-12-05 at 3 55 19 PM

## Alternatives
You might suggest your designer take a visual design 101 refresher course, or encourage them to slow down and try focus on being a little more "detail oriented".

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #339, "Update tag styling on homepage so it doesn't hurt user's eyes".

*Estimated review size: tiny, <5 minutes*

Solution
========
- Updates styling on "In Review" flag to a border and grey text.

Screenshots (optional):
-----------------------
Before:
image

After:
image

### CODE REVIEW

File: website/components/LandingPage/index.tsx [hunk 1]
```diff
@@ -209,15 +209,15 @@ const DatasetCard = styled.li`
 const InReviewFlag = styled(FlexRowAlignCenter)`
   border-radius: 4px;
   padding: 1px 6px;
-  background-color: var(--color-statusflag-bg);
-  height: 22px;
+  border: solid 1px var(--color-statusflag-border);
```
Comment (frasercl) [inline website/components/LandingPage/index.tsx:212]: I thought the standard order for `border` was thickness then style, i.e. `border: 1px solid ...;`, but this also seems to work everywhere I try it? Optionally consider changing for consistency though, the other order is what's used elsewhere in the codebase:

```suggestion
  border: 1px solid var(--color-statusflag-border);
```

**Review by frasercl — APPROVED** [review]
👍

**Review by interim17 — APPROVED** [review]
