### PR TITLE
fix: Shorten URLs

### LINKED ISSUE #302: Decrease URL length
## Use Case

- URLs are very long which may run into limits on some browsers
- URL encoding makes the URLs difficult to parse

## Solution
- Skip encoding on colons and commas
- Consider removing values that match default settings

## Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them_

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Closes #302, decreasing URL length.

*Estimated review size: large, 30-40 minutes*
(Many of the changes are unit tests.)

Before:
> https://volumeviewer.allencell.org/viewer?url=https%253A%252F%252Fallencell.s3.amazonaws.com%252Faics%252Fnuc_morph_data%252Fdata_for_analysis%252Fbaseline_colonies%252F20200323_06_mid%252Fraw.ome.zarr%2Chttps%253A%252F%252Fallencell.s3.amazonaws.com%252Faics%252Fnuc_morph_data%252Fdata_for_analysis%252Fbaseline_colonies%252F20200323_06_mid%252Fseg.ome.zarr&mode=volumetric&mask=0&image=cell&axes=0&bb=0&bbcol=ffffff&bgcol=000000&rot=0&bright=70&dens=2.5&interp=1&reg=0%3A1%2C0%3A1%2C0%3A1&slice=0.5%2C0.5%2C0.5&lvl=35%2C140%2C255&t=0&view=Z&c0=ven%3A1%2Csen%3A0%2Cisv%3A128%2Cisa%3A1%2Cclz%3A0%2Ccza%3A1%2Ccol%3Ac3c3c3%2Ccps%3A-26.64179104477612%253A0%253Affffff%252C58.66417910447761%253A0%253Affffff%252C136.7611940298507%253A1%253Affffff%252C279.73880597014926%253A1%253Affffff%2Ccpe%3A0%2Crmp%3A58.66417910447761%253A136.7611940298507&c1=ven%3A0%2Csen%3A0%2Cisv%3A128%2Cisa%3A1%2Cclz%3A0%2Ccza%3A1%2Ccol%3A6fba11%2Ccps%3A0%253A0%253Affffff%252C98%253A0%253Affffff%252C115%253A1%253Affffff%252C255%253A1%253Affffff%2Ccpe%3A0%2Crmp%3A98%253A115&c2=ven%3A1%2Csen%3A0%2Cisv%3A128%2Cisa%3A1%2Cclz%3A1%2Ccza%3A1%2Ccol%3A8da3c0%2Ccps%3A0%253A0%253Affffff%252C88%253A1%253Affffff%252C255%253A1%253Affffff%2Ccpe%3A0%2Crmp%3A0%253A255

After:
> http://volumeviewer.allencell.org/viewer?url=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc_morph_data%2Fdata_for_analysis%2Fbaseline_colonies%2F20200323_06_mid%2Fraw.ome.zarr,https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc_morph_data%2Fdata_for_analysis%2Fbaseline_colonies%2F20200323_06_mid%2Fseg.ome.zarr&dens=2.5&view=Z&c0=ven:1,col:c3c3c3,cps:0:0:1:88.701:0:1:111.53:1:1:255:1:1,rmp:26.035:138.78&c1=col:6fba11,cps:0:0:1:98:0:1:115:1:1:255:1:1,rmp:98:115&c2=ven:1,clz:1,col:8da3c0,cps:0:0:1:88:1:1:255:1:1

## Changes
- Channel settings no longer have `:` and `,` characters escaped.
- Changes the arrays for control points in the channel settings and camera vectors to use `:` as separators (instead of a mix of `,` and `:`) to reduce escaped characters.
  - Instead of `x1:y1:z1`**`,`**`x2:y2:z2`, sequences of number arrays/vectors are stored as `x1:y1:z1`**`:`**`x2:y2:z2`, with a colon in between.
  - Also adds backwards compatibility with the older control points encodings.
  - Cameras do not have backwards compatibility because they were just merged in #299 and are not in production yet.
- The `ffffff` default control point color is replaced with a designated placeholder (`1`).
- Default settings are not included in the exported URL.
- Adds formatting for float values to shorten the number of digits they display.

### CODE REVIEW

**Comment by ShrimpCryptid** [comment]
TODO:
- [ ] Test backwards compatibility for control point encodings
- [ ] Verify that channels that are set to default-only do not get left out of the URL
- [ ] Ignore default colors in channel state
- [ ] Add unit tests for checking removal of viewer settings and channel state defaults

File: website/components/Modals/ShareModal.tsx [hunk 1]
```diff
@@ -50,8 +50,12 @@ const ShareModal: React.FC<ShareModalProps> = (props: ShareModalProps) => {
     serializedViewerParams = { url: serializedUrl, ...serializedViewerParams };
   }
 
+  // TODO: Don't use URLSearchParams here because it will encode commas and colons?
   const params: URLSearchParams = new URLSearchParams(serializedViewerParams);
-  const shareUrl = params.size > 0 ? `${baseUrl}?${params.toString()}` : baseUrl;
+  let shareUrl = params.size > 0 ? `${baseUrl}?${params.toString()}` : baseUrl;
+
+  // Decode specifically colons and commas
+  shareUrl = shareUrl.replace(/%3A/g, ":").replace(/%2C/g, ",");
```
Comment (ShrimpCryptid) [inline website/components/Modals/ShareModal.tsx:58]: TODO: Turn this into a constant

File: website/utils/url_utils.ts [hunk 2]
```diff
@@ -419,16 +436,6 @@ function colorArrayToHex(color: ColorArray): string {
...
-function removeUndefinedProperties<T>(obj: T): Partial<T> {
-  const result: Partial<T> = {};
-  for (const key in obj) {
-    if (obj[key] !== undefined) {
-      result[key] = obj[key];
-    }
-  }
-  return result;
-}
-
```
Comment (ShrimpCryptid) [inline website/utils/url_utils.ts:431]: Moved to `datatype_utils.ts`

File: website/utils/test/datatype_utils.test.ts [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+    expect(isDeepEqual(a, b)).toBe(true);
+
+    b = [
+      { x: 1, opacity: 1, color: [255, 255, 255] },
+      { x: 50, opacity: 4.7, color: [128, 128, 255] },
+      { x: 128, opacity: 0.5, color: [0, 255, 1] },
+    ];
+    expect(isDeepEqual(a, b)).toBe(false);
+  });
+});
```
Comment (ShrimpCryptid) [inline website/utils/test/datatype_utils.test.ts:99]: Test with a `c` that's the same as `getObject` but only change one element of the colors.

File: website/components/Modals/ShareModal.tsx [hunk 4]
```diff
@@ -51,7 +51,10 @@ const ShareModal: React.FC<ShareModalProps> = (props: ShareModalProps) => {
   }
 
   const params: URLSearchParams = new URLSearchParams(serializedViewerParams);
-  const shareUrl = params.size > 0 ? `${baseUrl}?${params.toString()}` : baseUrl;
+  let shareUrl = params.size > 0 ? `${baseUrl}?${params.toString()}` : baseUrl;
+
+  // Decode specifically colons and commas for better readability + decreased char count
+  shareUrl = shareUrl.replace(ENCODED_COLON_REGEX, ":").replace(ENCODED_COMMA_REGEX, ",");
```
Comment (ShrimpCryptid) [inline website/components/Modals/ShareModal.tsx:57]: Fix this so it only escapes `params.toString()` and not the base Url.

File: website/utils/url_utils.ts [hunk 5]
```diff
@@ -32,10 +38,16 @@ const SLICE_REGEX = /^[0-9.]*,[0-9.]*,[0-9.]*$/;
...
- * Matches a comma-separated list of control points, where each control point is represented
+ * LEGACY: Matches a COMMA-separated list of control points, where each control point is represented
+ * by a triplet of `{x}:{opacity}:{hex color}`.
+ */
+export const LEGACY_CONTROL_POINTS_REGEX =
+  /^(-?[0-9.]*:[0-9.]*:([0-9a-fA-F]{6})?)(,-?[0-9.]*:[0-9.]*:([0-9a-fA-F]{6})?)*$/;
+/**
+ * Matches a COLON-separated list of control points, where each control point is represented
  * by a triplet of `{x}:{opacity}:{hex color}`.
  */
```
Comment (ShrimpCryptid) [inline website/utils/url_utils.ts:49]: Document that `w` is an acceptable replacement for `ffffff`

File: website/utils/url_utils.ts [hunk 6]
```diff
@@ -303,8 +315,8 @@ const tryDecodeURLList = (url: string, delim = ","): string[] | undefined => {
  * a key-value object.
  *
  * @param data The string to parse. Expected to be in the format
- * "key1:value1,key2:value2,...". Colons and commas in keys or values
- * should be encoded using `encodeURIComponent`.
+ * "key1:value1,key2:value2,...". Commas in keys or values
+ * must be encoded using `encodeURIComponent`.
```
Comment (ShrimpCryptid) [inline website/utils/url_utils.ts:319]: Possible bug here where commas can be decoded by ShareModal after being encoded in values. Maybe just explicitly forbid commas

File: website/utils/url_utils.ts [hunk 7]
```diff
@@ -442,16 +450,28 @@ function parseStringSlice(region: string | undefined): PerAxis<number> | undefin
...
+ * @param options Optional parameters for parsing:
+ * - `min`: Minimum value for each number. Default is negative infinity.
+ * - `max`: Maximum value for each number. Default is positive infinity.
+ * - `separator`: Separator between numbers. Default is `,`.
+ * @returns
+ * - undefined if the string is undefined or could not be parsed.
+ * - An array of three numbers, clamped to the [min, max] range.
  */
 function parseThreeNumberArray(
   levels: string | undefined,
```
Comment (ShrimpCryptid) [inline website/utils/url_utils.ts:463]: rename this to array/vector

File: website/utils/url_utils.ts [hunk 8]
```diff
@@ -822,14 +935,18 @@ export async function parseViewerUrlParams(urlSearchParams: URLSearchParams): Pr
  * Serializes the ViewerState and ChannelState of a ViewerStateContext into a URLSearchParams object.
  * @param state ViewerStateContext to serialize.
```
Comment (ShrimpCryptid) [inline website/utils/url_utils.ts:936]: Method comment for removeDefaults

File: website/utils/url_utils.ts (hunk 6 above)
Comment (ShrimpCryptid) [reply website/utils/url_utils.ts:319]: This will be fine actually, since URLParams does one level of encoding

File: src/aics-image-viewer/shared/constants.ts [hunk 9]
```diff
@@ -110,9 +110,17 @@ export const DEFAULT_VIEWER_SETTINGS: ViewerState = {
...
+    position: [0, 0, 5],
+    target: [0, 0, 0],
+    up: [0, 1, 0],
+    fov: 20,
+    orthoScale: 0.5,
+  },
 };
 
+// TODO: Make this and the default viewer settings lambda functions that return
+// new objects to prevent accidental mutation of the default state.
```
Comment (toloudis) [inline src/aics-image-viewer/shared/constants.ts:123]: yes do that 😄

File: website/components/Modals/ShareModal.tsx (hunk 4 above)
Comment (toloudis) [reply website/components/Modals/ShareModal.tsx:57]: make sure its only replacing on the part of the params excluding the serializedUrl (I believe the `url=` param should stay untouched)

File: website/utils/datatype_utils.ts [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+  }
+  return true;
+}
+
+/**
+ * Recursively checks for deep equality between two elements, including objects or arrays.
+ * @returns true if `a` and `b` are deeply equal, false otherwise. Handles NaN values
+ * and nested arrays.
+ */
+export function isDeepEqual(a: unknown, b: unknown): boolean {
```
Comment (toloudis) [inline website/utils/datatype_utils.ts:45]: see if the lodash deep equality check will work here

File: website/utils/test/url_utils.test.ts [hunk 11]
```diff
@@ -33,19 +35,46 @@ const defaultSettings: ViewerChannelSetting = {
...
+    const data = "1:0.5:ff0000,128:0.7:ffff00,255:1:ff0000";
+    expect(LEGACY_CONTROL_POINTS_REGEX.test(data)).toBe(true);
+  });
+
+  it("accepts negative numbers", () => {
+    const data = "-1:0.5:ff0000,-255:1:ff0000";
+    expect(LEGACY_CONTROL_POINTS_REGEX.test(data)).toBe(true);
+  });
+
+  it("allows 'w' as a placeholder for color strings", () => {
```
Comment (toloudis) [inline website/utils/test/url_utils.test.ts:54]: also suggest allowing `0` for black, and `1` or (maybe more appropriately) `-1` for white, as well.  Something about that feels more consistent than having a non-numeric letter character.  See what you think. If not today, then we can consider it for a future PR.

File: website/utils/datatype_utils.ts (hunk 10 above)
Comment (ShrimpCryptid) [reply website/utils/datatype_utils.ts]: It does! Test that uses it passes :)

File: website/utils/test/url_utils.test.ts (hunk 11 above)
Comment (ShrimpCryptid) [reply website/utils/test/url_utils.test.ts:54]: I'll replace "w" with 1, but I think anymore than that is out of scope for now. I added a related TODO about refactoring the regular expressions to be more composable.

Comment (ShrimpCryptid) [reply website/utils/test/url_utils.test.ts:54]: There's a few commented-out code blocks in here that hint at that change!

File: src/aics-image-viewer/shared/constants.ts [hunk 12]
```diff
@@ -110,10 +110,18 @@ export const DEFAULT_VIEWER_SETTINGS: ViewerState = {
...
+    position: [0, 0, 5],
+    target: [0, 0, 0],
+    up: [0, 1, 0],
+    fov: 20,
+    orthoScale: 0.5,
+  },
+});
 
-export const DEFAULT_CHANNEL_STATE: ChannelState = {
+// TODO: Make this and the default viewer settings lambda functions that return
```
Comment (toloudis) [inline src/aics-image-viewer/shared/constants.ts:122]: can remove this TODO now

**Review by toloudis — APPROVED** [review]
