### PR TITLE
Fix/roi slider feedback

### LINKED ISSUE #72: Clipping slider numbers should update while dragging slider
## Use Case

The 3d view updates while the slider is being dragged, but the displayed numbers do not.  (It has the appearance of a bug, since the numbers are not reflecting what is shown onscreen.)

## Solution

Let the numbers update while the slider handles are being dragged.

## Alternatives

(If there's some reason not to do this... technical or otherwise)

### PR DESCRIPTION
**Pull request by frasercl**
Resolves a bunch of small UI feedback items and a few assorted code maintenance tasks.

### Clipping Sliders

Resolves #72 - clipping slider numbers now update while slider is being dragged. This prompted a number of internal behavior changes to `AxisClipSliders`; and the creation of a new component, `SmarterSlider`, which wraps `Nouislider` and pauses updates while the slider is being dragged.

Also: play buttons are lighter, and slice numbers should no longer wrap.

### Other UI polish

- Control panel: tightens up some spacing, colors, and sizes per Lyndsay's feedback. Notably: tabs no longer flash a white border when hovered.
- Toolbar: brings control styling to [specification](https://xd.adobe.com/view/904d6444-a800-48b6-8844-4f6f116d85ab-c51e/screen/5bd5a6b1-83e2-424b-9d0c-a47a15c0b3ba/specs/).

### Code maintenance

- Since I was adding another shared component anyways, I converted our other shared component, `SharedCheckBox`, to TypeScript and replaced the legacy lifecycle it was still using. With this change, the app is free from legacy lifecycle warnings, and should be upgrade-able to newer versions of React if we want.
- Added `@types/lodash` package to get type hints for Lodash functions.

### CODE REVIEW

File: src/aics-image-viewer/components/shared/SmarterSlider.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+type CallbackArgs = [values: any[], handle: number, unencodedValues: number[], tap: boolean, positions: number[]];
+
+/** A wrapper around `Nouislider` that prevents updates while the slider is being dragged. */
+export default class SmarterSlider extends React.Component<NouisliderProps, { inactive: boolean }> {
+  constructor(props: NouisliderProps) {
+    super(props);
+    this.state = { inactive: true };
+  }
+
+  shouldComponentUpdate = () => this.state.inactive;
```
Comment (toloudis) [inline src/aics-image-viewer/components/shared/SmarterSlider.tsx:13]: consider renaming `inactive` to something more specific like `blockedUpdates` or even `shouldUpdate`

**Review by toloudis — APPROVED** [review]
A couple fairly minor comments on the code but otherwise LGTM!
