### PR TITLE
Fix Z slider causing errors with 2d image

### LINKED ISSUE #263: pure 2d image can not display in xy mode?
## Description

Loading a 2D zarr and switching to xy mode gives error that min and max of slider can not be same value.

## Expected Behavior

Expect a 2d xy image to show in xy mode with no problems.

## Reproduction

https://allen-cell-animated.github.io/website-3d-cell-viewer/viewer/?url=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0/labels/0/

### PR DESCRIPTION
**Pull request by frasercl**
Review time: small (5-10min)

Resolves #263: Z slider no longer causes an error in 2D XY mode when viewing a 2D image.

The Z clipping slider isn't especially meaningful when viewing a 2d image anyways. Currently, it shows two completely immovable handles in 3d mode, and creates an error in 2d mode. So this PR is really about removing it when the image has no Z dimension in the first place.

Following feedback from @lynwilhelm and the rest of UX, removing the Z slider works like this:
- In 3D mode, it's just gone entirely
- In 2D mode, the play button disappears and the slider is replaced with a placeholder message. The labels "ROI" and "Z" are preserved.
  - Note that, while I don't have a 2D zarr time series to demonstrate in a screenshot below, this allows the condition where the time slider is present alongside the placeholder Z slider.

### Screenshots

3D mode:
image

2D mode:
image

### CODE REVIEW

File: src/aics-image-viewer/components/AxisClipSliders/index.tsx [hunk 1]
```diff
@@ -232,6 +239,9 @@ const AxisClipSliders: React.FC<AxisClipSlidersProps> = (props) => {
 
   const create3dAxisSlider = (axis: AxisName): React.ReactNode => {
```
Comment (ShrimpCryptid) [inline src/aics-image-viewer/components/AxisClipSliders/index.tsx:240]: When is a `3dAxisSlider` used vs. a `2dAxisSlider`? Trying to understand why this was returning null.

**Review by ShrimpCryptid — APPROVED** [review]
Looks good, left one comment!

**Review by blairlyons — APPROVED** [review]

**Comment by interim17** [comment]
@frasercl I see two approvals on this, removing myself, but if you want eyes on this again for any reason just re-request me!
