### PR TITLE
Fix/move axis and scale indicators with clipping drawer

### LINKED ISSUE #73: reconcile the 3d axis position with the clipping sliders
## Use Case

we wanted the 3d clipping sliders to be at the bottom of the 3d view so they have a chance to have a wider space.
However, the 3d axis display is presented at the lower left, and when the Clipping drawer is open, it overlays on top and hides the axes.

## Solution

Not certain of the best solution.  
* I can make a strong argument for not overlaying and instead resizing the view.  (Same goes for the toolbar).  
* However it might be a nice option to be able to specify which corner the axes go in (as a prop maybe?).  
* Also possibly we can just shift the axes up when the drawer is open.

### PR DESCRIPTION
**Pull request by frasercl**
## Problem

#73: the clipping panel covers the axis indicator when open.

The introduction of scale bars, which appear in the bottom-right corner of the viewport by default, creates a similar but worse problem: not only are scale bars covered by the open clipping panel, they are also covered by the button to open the clipping panel when the panel is closed.

## Solution

Use `View3d`'s new methods `setAxisPosition` and `setScaleBarPosition` to move the indicators out of the way. This requires adding a new prop `onVisibilityChange` to the `BottomPanel` component so that this state can be passed up. This resolves #73, though per comments on that issue it may be worth opening another ticket to investigate other related changes that can be made to the UI.

Additionally, the bottom panel button uses an icon from antd that's nearly identical to one of our own custom icons, so I replaced it with the custom icon, and upgraded the ergonomics of the `ViewerIcon` utility component along the way. (See comment on #102 for why we should prefer our own icons.)

## Screenshots
image
image
image

### CODE REVIEW

File: src/aics-image-viewer/components/App/index.tsx [hunk 1]
```diff
@@ -1035,8 +1040,36 @@ export default class App extends React.Component<AppProps, AppState> {
...
 
   onResetCamera(): void {
-    if (this.state.view3d) {
-      this.state.view3d.resetCamera();
+    this.state.view3d?.resetCamera();
+  }
+
+  onClippingPanelOpen(open: boolean): void {
+    const CLIPPING_PANEL_HEIGHT = 130;
+    const CLIPPING_PANEL_OPEN_TIME = 300;
```
Comment (toloudis) [inline src/aics-image-viewer/components/App/index.tsx:1048]: is this related to some value associated with opening a antd Drawer?  I wonder if we could get the correct actual value from somewhere else.

File: src/aics-image-viewer/components/App/index.tsx [hunk 2]
```diff
@@ -1035,8 +1040,36 @@ export default class App extends React.Component<AppProps, AppState> {
   changeBoundingBoxShowing = (showing: boolean): void => this.changeUserSelection("showBoundingBox", showing);
 
   onResetCamera(): void {
-    if (this.state.view3d) {
-      this.state.view3d.resetCamera();
+    this.state.view3d?.resetCamera();
+  }
+
+  onClippingPanelOpen(open: boolean): void {
+    const CLIPPING_PANEL_HEIGHT = 130;
```
Comment (toloudis) [inline src/aics-image-viewer/components/App/index.tsx:1047]: would be nice to get this height from somewhere else where it is specified

File: src/aics-image-viewer/components/App/index.tsx (hunk 1 above)
Comment (toloudis) [reply src/aics-image-viewer/components/App/index.tsx:1048]: Drawer has a `afterVisibleChange` prop which might help here?

**Review by toloudis — APPROVED** [review]
Do we need to get a UX review on this?
